"""AI pseudo-C enrichment overlay (never mutates IDA exports or IDBs).

Hex-Rays on unsigend MIPS/uClibc drops every call-site argument
("memcpy();") and keeps only register-annotated temporaries. The arguments
still exist in the instruction stream, so for each selected function the
pseudo-C plus the IDA disassembly (.asm, exported by ida_export.py) go to
the LLM, which returns JSON:
  renames    {"v2": "conn_fd", ...}        readable variable names
  call_args  {"memcpy()": "memcpy(v36, &v47, v42)", ...}  recovered calls
  summary    one-line purpose
  domain     http|net|auth|crypto|util|sys|unknown
  confidence 0..1
Functions whose decompile failed (.c missing) get a best-effort asm->C
synthetic translation instead (marked "synthetic": true in the overlay).

Overlays live in <md5>/ai/<addr>.json and <md5>/ai/<addr>.c. The original
.c files, symbols.json and IDBs stay byte-identical; every overlay records
model + source="ai" so AI output is always distinguishable from IDA output.

CLI: python -m pipeline.decompile.ai_enrich <job_id> <binary_md5> [--all] \
       [--no-failed] [--limit N]
"""

import json
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path

from pipeline.ailift import llm
from pipeline.ailift.runner import _attack_chain_addrs

FWGRAPH_ROOT = Path(__file__).resolve().parents[2]

MAX_CODE_CHARS = int(os.getenv("AI_ENRICH_MAX_CODE_CHARS", "6000"))
MAX_ASM_CHARS = int(os.getenv("AI_ENRICH_MAX_ASM_CHARS", "9000"))
# the anthropic gateway caps completion at 4096 tokens
ENRICH_MAX_TOKENS = int(os.getenv("AI_ENRICH_MAX_TOKENS", "16384"))  # reasoning models burn thought tokens before content; 4096 starved output

_SYSTEM = """You are a reverse-engineering assistant annotating Hex-Rays MIPS pseudo-C.
Hex-Rays lost all call-site arguments (bare "memcpy();") and all variable
names ("v1..v52"). The arguments still exist in the disassembly (MIPS o32
ABI: $a0-$a3 then the stack). Recover them.
Reply ONLY a JSON object:
{
 "renames": {"<old_name>": "<new_snake_case_name>"},
 "call_args": {"<bare call exactly as it appears, e.g. memcpy()>":
               "<recovered call with args, e.g. memcpy(v36, &v47, v42)>"},
 "summary": "<one line: what this function does>",
 "domain": "<http|net|auth|crypto|util|sys|unknown>",
 "confidence": <float 0..1>
}
Rules: never invent arguments not evidenced by the disassembly; leave
uncertain calls out of call_args; only rename variables you are confident
about; no prose outside the JSON object."""

_SYNTH_SYSTEM = """You are a reverse-engineering assistant translating MIPS
disassembly (uClibc userland, o32 ABI) into readable C. Hex-Rays failed on
this function, so the disassembly is all you have.
Reply ONLY a JSON object:
{
 "synthetic_c": "<plausible C translation, best effort>",
 "summary": "<one line: what this function does>",
 "domain": "<http|net|auth|crypto|util|sys|unknown>",
 "confidence": <float 0..1>
}
Rules: mark guesses with /* ? */ comments; no prose outside the JSON object."""


def _cfg(name, default):
    return os.getenv(name, default)


def _now():
    return datetime.now(timezone.utc).isoformat()


def _read(path):
    try:
        return Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _clip(text, limit):
    if text and len(text) > limit:
        return text[:limit] + "\n// ... [truncated]"
    return text or ""


def collect_targets(symbols, md5, pseudo_dir, addrs=None,
                    include_failed=False):
    """[(func, has_c)] for functions that have a .asm and pass the filters."""
    entry = symbols.get("binaries", {}).get(md5) or {}
    funcs_dir = Path(pseudo_dir) / "functions"
    targets = []
    for func in entry.get("functions", []):
        addr = func.get("addr", "")
        if addrs is not None and addr.lower() not in addrs:
            continue
        if not (funcs_dir / f"{addr}.asm").is_file():
            continue
        has_c = (funcs_dir / f"{addr}.c").is_file()
        if not has_c and not include_failed:
            continue
        targets.append((func, has_c))
    return targets


def _build_user(func, code, asm, has_c):
    parts = [
        f"function: {func.get('name')} @ {func.get('addr')} "
        f"(arch=mips32le, size={func.get('size')}, "
        f"calls={', '.join(func.get('calls') or []) or 'none'})",
    ]
    if has_c:
        parts.append("--- pseudo-C (Hex-Rays, arguments lost) ---")
        parts.append(_clip(code, MAX_CODE_CHARS))
    parts.append("--- disassembly (ground truth) ---")
    parts.append(_clip(asm, MAX_ASM_CHARS))
    return "\n".join(parts)


def render_overlay(func, has_c, code, parsed):
    """Render the human-readable overlay .c from one parsed LLM result."""
    lines = [
        f"// AI-ENRICHED OVERLAY - generated by {parsed.get('model') or 'llm'}, not by IDA",
        f"// addr={func.get('addr')} name={func.get('name')} "
        f"confidence={parsed.get('confidence')} domain={parsed.get('domain')}",
        f"// summary: {parsed.get('summary') or ''}",
        "",
    ]
    if has_c and code:
        text = code
        for old, new in sorted((parsed.get("renames") or {}).items()):
            old, new = str(old), str(new)
            if re.fullmatch(r"[A-Za-z_]\w*", old) \
                    and re.fullmatch(r"[A-Za-z_]\w*", new):
                text = re.sub(rf"\b{re.escape(old)}\b", new, text)
        for bare, recovered in (parsed.get("call_args") or {}).items():
            text = text.replace(str(bare), str(recovered))
        lines.append(text.rstrip("\n"))
    elif parsed.get("synthetic_c"):
        lines.append("// synthetic translation from disassembly "
                     "(Hex-Rays failed on this function)")
        lines.append(str(parsed["synthetic_c"]).rstrip("\n"))
    else:
        lines.append("// no usable AI output for this function")
    return "\n".join(lines) + "\n"


def _valid_overlay(parsed):
    if not isinstance(parsed, dict):
        return False
    if parsed.get("synthetic_c"):
        return True
    return bool(parsed.get("renames") or parsed.get("call_args")
                or parsed.get("summary"))


def run_enrich(job_id, data_dir, md5, addrs=None, attack_only=True,
               include_failed=True, limit=0, resume=True):
    """Enrich one binary's functions; returns the summary dict.

    addrs: explicit {addr} set (lowercase hex). attack_only intersects them
    with the attack-chain function set; with addrs=None it selects exactly
    the attack-chain set (AI_ATTACK_CHAINS_ONLY scenario). resume=True skips
    functions that already have an overlay (interrupted runs continue where
    they stopped); resume=False re-enriches everything.
    """
    data_dir = Path(data_dir)
    t0 = time.time()
    pseudo_root = data_dir / "pseudocode" / job_id
    symbols = json.loads(
        (pseudo_root / "symbols.json").read_text(encoding="utf-8"))
    if addrs is not None:
        addrs = {str(a).lower() for a in addrs}
    if attack_only:
        chain = _attack_chain_addrs(symbols, pseudo_root).get(md5, set())
        addrs = chain if addrs is None else (addrs & chain)
    pseudo_dir = pseudo_root / md5
    targets = collect_targets(symbols, md5, pseudo_dir, addrs, include_failed)
    if limit:
        targets = targets[:int(limit)]

    summary = {"job_id": job_id, "md5": md5, "status": "running",
                   "attack_only": attack_only, "include_failed": include_failed,
                   "created_at": _now(), "targets": len(targets),
                   "enriched": 0, "synthetic": 0, "errors": 0, "items": []}
    summary_path = pseudo_dir / "ai" / "ai_enrich.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    if resume:
        before = len(targets)
        targets = [(func, has_c) for func, has_c in targets
                   if not (summary_path.parent / f"{func['addr']}.json")
                   .is_file()]
        summary["resumed_skip"] = before - len(targets)
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    chunk_size = max(1, int(_cfg("AI_ENRICH_CHUNK", "8")))
    try:
        client = llm.LLMClient.from_env(
            usage_path=pseudo_root / "llm_usage.json")
        # enrichment prompts are ~15 KB with 2048-token answers: longer
        # timeout and gentler concurrency than the tiny ailift tag calls
        client.timeout = float(_cfg("AI_ENRICH_TIMEOUT", "300"))
        client.concurrency = int(_cfg("AI_ENRICH_CONCURRENCY", "4"))
        items = []
        for func, has_c in targets:
            code = _read(pseudo_dir / "functions" / f"{func['addr']}.c")
            asm = _read(pseudo_dir / "functions" / f"{func['addr']}.asm")
            items.append({
                "func": func, "has_c": has_c, "code": code,
                "system": _SYSTEM if has_c else _SYNTH_SYSTEM,
                "user": _build_user(func, code, asm or "", has_c),
                "max_tokens": ENRICH_MAX_TOKENS,
                "raw": True,
            })
        # chunk the batch: results are persisted per chunk, so a crash or
        # service restart never loses the whole run
        for start in range(0, len(items), chunk_size):
            for item, parsed, error in llm.suggest_batch(
                    client, items[start:start + chunk_size]):
                func, has_c = item["func"], item["has_c"]
                addr = func["addr"]
                if error or not _valid_overlay(parsed):
                    summary["errors"] += 1
                    summary["items"].append(
                        {"addr": addr, "status": "error",
                         "error": error or "empty AI output"})
                    continue
                parsed["model"] = client.model
                overlay = {
                    "addr": addr, "name": func.get("name"), "source": "ai",
                    "has_c": has_c, "synthetic": not has_c,
                    "model": client.model,
                    "renames": parsed.get("renames") or {},
                    "call_args": parsed.get("call_args") or {},
                    "summary": parsed.get("summary"),
                    "domain": parsed.get("domain"),
                    "confidence": parsed.get("confidence"),
                }
                if not has_c:
                    overlay["synthetic_c"] = parsed.get("synthetic_c")
                ai_dir = pseudo_dir / "ai"
                (ai_dir / f"{addr}.json").write_text(
                    json.dumps(overlay, indent=2), encoding="utf-8")
                (ai_dir / f"{addr}.c").write_text(
                    render_overlay(func, has_c, item["code"], parsed),
                    encoding="utf-8")
                summary["enriched"] += 1
                summary["synthetic"] += 0 if has_c else 1
                summary["items"].append({
                    "addr": addr, "status": "ok", "synthetic": not has_c,
                    "renames": len(overlay["renames"]),
                    "call_args": len(overlay["call_args"]),
                    "confidence": overlay["confidence"],
                    "summary": overlay["summary"],
                })
            summary_path.write_text(json.dumps(summary, indent=2),
                                    encoding="utf-8")
        summary["status"] = "ok"
    except Exception as exc:  # noqa: BLE001 - any failure lands in the summary
        summary["status"] = "failed"
        summary["error"] = f"{type(exc).__name__}: {exc}"
    summary["elapsed_seconds"] = round(time.time() - t0, 2)
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 1
    from dotenv import load_dotenv
    load_dotenv(FWGRAPH_ROOT / ".env")
    data_dir = Path(_cfg("FWGRAPH_DATA", str(FWGRAPH_ROOT / "data")))
    summary = run_enrich(
        argv[1], data_dir, argv[2],
        attack_only="--all" not in argv,
        include_failed="--no-failed" not in argv,
        limit=int(argv[argv.index("--limit") + 1]) if "--limit" in argv else 0)
    print(json.dumps({k: summary[k] for k in
                      ("status", "targets", "enriched", "synthetic",
                       "errors", "elapsed_seconds")}, indent=2))
    return 0 if summary["status"] == "ok" else 1


if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv))
